service: solarpal-api
frameworkVersion: '>=1.28.0'
provider:
  name: aws
  runtime: go1.x
  region: eu-north-1
  stage: ${opt:stage}
functions:
  solarpal-api:
    handler: bin/solarpal
    events: 
      - http:
         path: /
         method: GET
package: 
  - '!*/**'
  - bin/solarpal